name: tests

on:
  push:
    branches:
      - main
      - feature-ci-*
  pull_request:
    branches:
      - main
      - feature-ci-*

jobs:
  lotus-test:
    name: lotus-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          # 'ubuntu-latest', 
          'macos-latest'
          # 'windows-latest'
        ]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Run tests
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
          R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
        shell: bash -l {0}
        run: |
           bash tests/tests.sh
