name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 
          'ubuntu-latest', 
          'macos-latest' 
          # 'windows-latest' writes_delim with na="" fails
        ]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Run tests
        run: |
          cp -R config/default config/params
          bash tests/tests.sh
